import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { test } from "node:test";

test("member admin stays a thin, confirmed, role-aware command API consumer", async () => {
  const source = await readFile(
    new URL("./LiveDashboard.astro", import.meta.url),
    "utf8",
  );
  assert.match(source, /\.select\("user_id,display_name,role"\)/);
  assert.match(source, /me\?\.role === "owner"/);
  assert.match(source, /me\?\.role === "admin" && member\.role !== "owner"/);
  assert.match(source, /window\.confirm\(/);
  assert.match(source, /removeWorkspaceMember\(/);
  assert.match(source, /error instanceof FreshLoginRequired/);
  assert.match(source, /pending-member-selection/);
  /*
   * The OAuth control in the re-authentication block is generated by ProviderButtons and
   * bound by provider id, so this file names no provider. The pin is on the WIRING: the
   * block's generated buttons reach signInWithProvider, which runs the id through
   * authProvider(). components/auth/provider-buttons.observer.test.ts owns the claim that
   * the buttons themselves are generated and carry the constant's labels.
   */
  assert.match(
    source,
    /\[data-member-reauth\] \[data-signin-provider\][\s\S]*?signInWithProvider\(/,
  );
  /*
   * The retired spelling, pinned as an ELEMENT rather than as a string: the template's own
   * comment still names `data-member-reauth-github` so a reader who greps for it lands on the
   * reason it went away, and a comment is not a control.
   */
  assert.doesNotMatch(
    source,
    /<[a-zA-Z][^>]*\bdata-member-reauth-github\b/,
    "the re-authentication OAuth button must not name a provider in its attribute. That " +
      "spelling WAS invisible to the provider sweep, which is how it shipped; the sweep sees " +
      "it now, and this keeps the control generated rather than merely counted.",
  );
  assert.match(source, /\[data-member-reauth-email\][\s\S]*?signInWithEmail\(/);
  assert.match(source, /press Remove again/);
  assert.doesNotMatch(
    source,
    /getItem\(\s*"commonswarm\.pending-member-selection"/,
    "returning from reauthentication must never auto-run removal",
  );
});

test("browser command helper posts strict remove_member and names recovery", async () => {
  const source = await readFile(
    new URL("../../lib/commonswarm.ts", import.meta.url),
    "utf8",
  );
  assert.match(source, /\{ kind: "remove_member", user_id: userId \}/);
  assert.match(source, /workspace_id: workspaceId/);
  assert.match(source, /stream: \{ kind: "workspace" \}/);
  assert.match(source, /fresh_auth_required/);
  assert.match(source, /landing_authority_unresolved/);
  assert.match(source, /separate audited transfer command/);
});
